# Generated by Django 3.0.4 on 2020-07-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20200713_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nancy',
            name='imagefile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
