# Generated by Django 3.0.4 on 2020-07-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20200713_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nancy',
            name='imagefile',
            field=models.ImageField(blank=True, null=True, upload_to='nancy/images'),
        ),
    ]
