# Generated by Django 3.0.4 on 2020-07-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20200713_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nancy',
            name='imagefile',
            field=models.ImageField(default='todo\\static\nancy\\images\\Mashed_apple.png', upload_to='nancy/images'),
        ),
    ]
