# Generated by Django 3.0.4 on 2020-07-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20200714_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='nancy',
            name='scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
