# Generated by Django 3.0.4 on 2020-07-14 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_nancy_scheduled'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
