# Generated by Django 2.2.4 on 2020-07-20 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_delete_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nancy',
            old_name='Ingredients',
            new_name='mainIngredient',
        ),
    ]
